// Egyptian Cities mapping from English to Arabic
export const cityMapping = {
  // Cairo Governorate
  "Cairo": "القاهرة",
  "Giza": "الجيزة", 
  "Helwan": "حلوان",
  "6th of October": "السادس من أكتوبر",
  "Sheikh Zayed": "الشيخ زايد",
  "New Cairo": "القاهرة الجديدة",
  "Shoubra": "شبرا",
  "Maadi": "المعادي",
  "Zamalek": "الزمالك",
  "Nasr City": "مدينة نصر",
  "Heliopolis": "مصر الجديدة",
  "Ain Shams": "عين شمس",
  "El Mokattam": "المقطم",
  "El Basatin": "البساتين",
  "El Sayeda Zeinab": "السيدة زينب",
  "El Darb El Ahmar": "الدرب الأحمر",
  "El Gamaleya": "الجمالية",
  "El Khalifa": "الخليفة",
  "El Mounira": "المنيرة",
  "El Sakakini": "السكاكيني",
  "El Shorouk": "الشروق",
  "El Tagamoa El Khames": "التجمع الخامس",
  "El Rehab": "الرحاب",
  "El Obour": "العبور",
  "El Badrasheen": "البدرشين",
  "El Haram": "الهرم",
  "El Hawamdeya": "الحوامدية",
  "El Saff": "الصف",
  "El Ayyat": "العياط",
  "El Kattameya": "القطامية",
  "El Shorouk": "الشروق",
  "El Rehab": "الرحاب",
  "El Obour": "العبور",
  "El Badrasheen": "البدرشين",
  "El Haram": "الهرم",
  "El Hawamdeya": "الحوامدية",
  "El Saff": "الصف",
  "El Ayyat": "العياط",
  "El Kattameya": "القطامية",
  
  // Alexandria Governorate
  "Alexandria": "الإسكندرية",
  "Borg El Arab": "برج العرب",
  "Borg El Arab Industrial": "برج العرب الصناعية",
  "El Amreya": "العامرية",
  "El Agami": "العجمي",
  "El Dekheila": "الدخيلة",
  "El Montazah": "المنتزه",
  "El Raml": "الرمل",
  "El Gomrok": "الجمهور",
  "El Labban": "اللبان",
  "El Mansheya": "المنشية",
  "El Moharam Bek": "المحرم بك",
  "El Saba Pasha": "سابا باشا",
  "El Shatby": "الشاطبي",
  "El Wardian": "الورديان",
  "Karmouz": "كرموز",
  "Miami": "ميامي",
  "Sidi Gaber": "سيدي جابر",
  "Smouha": "سموحة",
  "Stanley": "ستانلي",
  "Victoria": "فيكتوريا",
  
  // Giza Governorate
  "Dokki": "الدقي",
  "Mohandessin": "المهندسين",
  "Agouza": "العجوزة",
  "Faisal": "فيصل",
  "Haram": "الهرم",
  "Omraneya": "العمرانية",
  "Boulaq El Dakrour": "بولاق الدكرور",
  "El Ayyat": "العياط",
  "El Badrasheen": "البدرشين",
  "El Hawamdeya": "الحوامدية",
  "El Saff": "الصف",
  "El Kattameya": "القطامية",
  "El Shorouk": "الشروق",
  "El Rehab": "الرحاب",
  "El Obour": "العبور",
  "El Badrasheen": "البدرشين",
  "El Haram": "الهرم",
  "El Hawamdeya": "الحوامدية",
  "El Saff": "الصف",
  "El Ayyat": "العياط",
  "El Kattameya": "القطامية",
  
  // Port Said Governorate
  "Port Said": "بورسعيد",
  "Port Fouad": "بورفؤاد",
  "El Arab": "العرب",
  "El Sharq": "الشرق",
  "El Manakh": "المناخ",
  "El Zohour": "الزهور",
  "El Dawahy": "الضواحي",
  "El Salam": "السلام",
  "El Shohada": "الشهداء",
  
  // Suez Governorate
  "Suez": "السويس",
  "El Arbaeen": "الأربعين",
  "Faisal": "فيصل",
  "Attaka": "عتاقة",
  "El Ganayen": "الجنائن",
  
  // Ismailia Governorate
  "Ismailia": "الإسماعيلية",
  "El Qantara": "القطارة",
  "El Qantara Sharq": "القطارة شرق",
  "Fayed": "فايد",
  "El Tal El Kebir": "التل الكبير",
  "Abu Suweir": "أبو صوير",
  "Kassaseen": "القصاصين",
  
  // Damietta Governorate
  "Damietta": "دمياط",
  "Ras El Bar": "رأس البر",
  "El Zarqa": "الزرقا",
  "Kafr Saad": "كفر سعد",
  "Kafr El Battikh": "كفر البطيخ",
  "El Senga": "السناجا",
  "Miet Abou Ghalib": "ميت أبو غالب",
  "El Nour": "النور",
  "El Qod": "القد",
  "El Qod": "القد",
  
  // Dakahlia Governorate
  "Mansoura": "المنصورة",
  "Talkha": "طلخا",
  "Mit Ghamr": "ميت غمر",
  "Dekernes": "دكرنس",
  "Aga": "أجا",
  "Minyet El Nasr": "منية النصر",
  "Sinbillawin": "سنبلاوين",
  "El Kurdi": "الكردي",
  "Bani Ebeid": "بني عبيد",
  "El Matareya": "المطرية",
  "Belqas": "بلقاس",
  "Sherbin": "شربين",
  "El Senbellawein": "السنبلاوين",
  "El Gamaliya": "الجمالية",
  "El Manzala": "المنزلة",
  "Temay El Amdid": "تمي الأمديد",
  "El Zarka": "الزرقا",
  "Shirbin": "شربين",
  "Mit El Kholy": "ميت الخولي",
  "El Gamaliya": "الجمالية",
  "El Manzala": "المنزلة",
  "Temay El Amdid": "تمي الأمديد",
  "El Zarka": "الزرقا",
  "Shirbin": "شربين",
  "Mit El Kholy": "ميت الخولي",
  
  // Gharbia Governorate
  "Tanta": "طنطا",
  "El Mahalla El Kubra": "المحلة الكبرى",
  "Kafr El Zayat": "كفر الزيات",
  "Zefta": "زفتى",
  "El Santa": "السنطة",
  "Qutur": "قطور",
  "Basyoun": "بسيون",
  "Samanoud": "سمنود",
  "El Hamool": "الحامول",
  "Kotour": "قطور",
  "Basyoun": "بسيون",
  "Samanoud": "سمنود",
  "El Hamool": "الحامول",
  
  // Menoufia Governorate
  "Shibin El Kom": "شبين الكوم",
  "El Bagour": "الباجور",
  "Quesna": "قويسنا",
  "El Shohada": "الشهداء",
  "Tala": "تلا",
  "Berket El Sabaa": "بركة السبع",
  "El Sadat": "السادات",
  "Menouf": "منوف",
  "Ashmoun": "أشمون",
  "El Qanatir El Khairiya": "القناطر الخيرية",
  "Tukh": "طوخ",
  "El Shohada": "الشهداء",
  "Tala": "تلا",
  "Berket El Sabaa": "بركة السبع",
  "El Sadat": "السادات",
  "Menouf": "منوف",
  "Ashmoun": "أشمون",
  "El Qanatir El Khairiya": "القناطر الخيرية",
  "Tukh": "طوخ",
  
  // Qalyubia Governorate
  "Banha": "بنها",
  "Qalyub": "قليوب",
  "El Khanka": "الخانكة",
  "Kafr Shukr": "كفر شكر",
  "Tukh": "طوخ",
  "El Qanatir El Khairiya": "القناطر الخيرية",
  "Shubra El Kheima": "شبرا الخيمة",
  "El Obour": "العبور",
  "El Shorouk": "الشروق",
  "El Rehab": "الرحاب",
  "El Badrasheen": "البدرشين",
  "El Haram": "الهرم",
  "El Hawamdeya": "الحوامدية",
  "El Saff": "الصف",
  "El Ayyat": "العياط",
  "El Kattameya": "القطامية",
  
  // Sharqia Governorate
  "Zagazig": "الزقازيق",
  "El Husseiniya": "الحسينية",
  "Abu Hammad": "أبو حماد",
  "El Qurein": "القرين",
  "Abu Kebir": "أبو كبير",
  "Faqous": "فاقوس",
  "El Ibrahimiya": "الإبراهيمية",
  "Hihya": "ههيا",
  "Awlad Saqr": "أولاد صقر",
  "El Salhiya": "الصالحية",
  "Minshat El Qanater": "منشأة القناطر",
  "Mashtoul El Souq": "مشتول السوق",
  "Qenaiat": "قنايات",
  "El Qanayat": "القنايات",
  "El Qurein": "القرين",
  "Abu Kebir": "أبو كبير",
  "Faqous": "فاقوس",
  "El Ibrahimiya": "الإبراهيمية",
  "Hihya": "ههيا",
  "Awlad Saqr": "أولاد صقر",
  "El Salhiya": "الصالحية",
  "Minshat El Qanater": "منشأة القناطر",
  "Mashtoul El Souq": "مشتول السوق",
  "Qenaiat": "قنايات",
  "El Qanayat": "القنايات",
  
  // Kafr El Sheikh Governorate
  "Kafr El Sheikh": "كفر الشيخ",
  "Desouk": "دسوق",
  "Fuwa": "فوة",
  "Metoubes": "مطوبس",
  "Baltim": "بلطيم",
  "Sidi Salem": "سيدي سالم",
  "Qallin": "قلين",
  "Sidi Ghazi": "سيدي غازي",
  "El Hamool": "الحامول",
  "Biyala": "بيالة",
  "El Reyad": "الرياض",
  "El Borollos": "البرلس",
  "El Hamool": "الحامول",
  "Biyala": "بيالة",
  "El Reyad": "الرياض",
  "El Borollos": "البرلس",
  
  // Beheira Governorate
  "Damanhour": "دمنهور",
  "Rashid": "رشيد",
  "Kafr El Dawwar": "كفر الدوار",
  "Abu El Matamir": "أبو المطامير",
  "Abu Hummus": "أبو حمص",
  "El Delengat": "الدلنجات",
  "El Mahmoudiya": "المحمودية",
  "El Rahmaniya": "الرحمانية",
  "Edko": "إدكو",
  "Kom Hamada": "كوم حمادة",
  "El Nubaria": "النوبارية",
  "Wadi El Natrun": "وادي النطرون",
  "El Delengat": "الدلنجات",
  "El Mahmoudiya": "المحمودية",
  "El Rahmaniya": "الرحمانية",
  "Edko": "إدكو",
  "Kom Hamada": "كوم حمادة",
  "El Nubaria": "النوبارية",
  "Wadi El Natrun": "وادي النطرون",
  
  // Fayoum Governorate
  "Fayoum": "الفيوم",
  "Fayoum El Gedida": "الفيوم الجديدة",
  "Tamiya": "طامية",
  "Sinnuris": "سنورس",
  "Etsa": "إطسا",
  "El Atsa": "العاطس",
  "Yousef El Seddik": "يوسف الصديق",
  "El Fashn": "الفحص",
  "Biyaso": "بياضو",
  "El Fashn": "الفحص",
  "Biyaso": "بياضو",
  
  // Beni Suef Governorate
  "Beni Suef": "بني سويف",
  "El Fashn": "الفحص",
  "Biyaso": "بياضو",
  "El Wasta": "الوسطى",
  "Nasser": "ناصر",
  "El Fashn": "الفحص",
  "Biyaso": "بياضو",
  "El Wasta": "الوسطى",
  "Nasser": "ناصر",
  
  // Minya Governorate
  "Minya": "المنيا",
  "El Minya": "المنيا",
  "Maghagha": "مغاغة",
  "Beni Mazar": "بني مزار",
  "Matai": "مطاي",
  "Samalut": "سمالوط",
  "El Idwa": "العدوة",
  "Mallawi": "ملوي",
  "Deir Mawas": "دير مواس",
  "Abu Qurqas": "أبو قرقاص",
  "El Idwa": "العدوة",
  "Mallawi": "ملوي",
  "Deir Mawas": "دير مواس",
  "Abu Qurqas": "أبو قرقاص",
  
  // Assiut Governorate
  "Assiut": "أسيوط",
  "El Fath": "الفتح",
  "Abu Tig": "أبو تيج",
  "El Ghanayem": "الغنايم",
  "Sahel Selim": "ساحل سليم",
  "El Badari": "البداري",
  "Sidfa": "صدفا",
  "El Qusiya": "القسية",
  "Manfalut": "منفلوط",
  "El Fath": "الفتح",
  "Abu Tig": "أبو تيج",
  "El Ghanayem": "الغنايم",
  "Sahel Selim": "ساحل سليم",
  "El Badari": "البداري",
  "Sidfa": "صدفا",
  "El Qusiya": "القسية",
  "Manfalut": "منفلوط",
  
  // Sohag Governorate
  "Sohag": "سوهاج",
  "Akhmim": "أخميم",
  "El Balyana": "البلينا",
  "El Maragha": "المراغة",
  "El Monshah": "المنشأة",
  "Dar El Salam": "دار السلام",
  "Girga": "جرجا",
  "Tahta": "طهطا",
  "El Balyana": "البلينا",
  "El Maragha": "المراغة",
  "El Monshah": "المنشأة",
  "Dar El Salam": "دار السلام",
  "Girga": "جرجا",
  "Tahta": "طهطا",
  
  // Qena Governorate
  "Qena": "قنا",
  "El Waqf": "الوقف",
  "Qus": "قوص",
  "Naqada": "نقادة",
  "Farshout": "فرشوط",
  "Abu Tesht": "أبو تشت",
  "El Waqf": "الوقف",
  "Qus": "قوص",
  "Naqada": "نقادة",
  "Farshout": "فرشوط",
  "Abu Tesht": "أبو تشت",
  
  // Luxor Governorate
  "Luxor": "الأقصر",
  "El Karnak": "الكرنك",
  "El Armant": "الأرمنت",
  "Esna": "إسنا",
  "El Tod": "الطود",
  "El Bayadiya": "البياضية",
  "El Qarna": "القرنة",
  "El Karnak": "الكرنك",
  "El Armant": "الأرمنت",
  "Esna": "إسنا",
  "El Tod": "الطود",
  "El Bayadiya": "البياضية",
  "El Qarna": "القرنة",
  
  // Aswan Governorate
  "Aswan": "أسوان",
  "Abu Simbel": "أبو سمبل",
  "Kalabsha": "كلابشة",
  "Edfu": "إدفو",
  "Kom Ombo": "كوم أمبو",
  "Daraw": "دراو",
  "Abu Simbel": "أبو سمبل",
  "Kalabsha": "كلابشة",
  "Edfu": "إدفو",
  "Kom Ombo": "كوم أمبو",
  "Daraw": "دراو",
  
  // Red Sea Governorate
  "Hurghada": "الغردقة",
  "El Gouna": "الجونة",
  "Safaga": "سفاجا",
  "El Quseir": "القصير",
  "Marsa Alam": "مرسى علم",
  "Shalateen": "شلاتين",
  "Halayeb": "حلايب",
  "El Gouna": "الجونة",
  "Safaga": "سفاجا",
  "El Quseir": "القصير",
  "Marsa Alam": "مرسى علم",
  "Shalateen": "شلاتين",
  "Halayeb": "حلايب",
  
  // New Valley Governorate
  "El Kharga": "الخارجة",
  "El Dakhla": "الداخلة",
  "El Farafra": "الفرافرة",
  "El Bahariya": "البحرية",
  "El Dakhla": "الداخلة",
  "El Farafra": "الفرافرة",
  "El Bahariya": "البحرية",
  
  // Matrouh Governorate
  "Marsa Matrouh": "مرسى مطروح",
  "El Alamein": "العلمين",
  "El Dabaa": "الضبعة",
  "El Hamam": "الحمام",
  "El Negaila": "النجيلة",
  "Sidi Barrani": "سيدي براني",
  "Sallum": "السلوم",
  "El Alamein": "العلمين",
  "El Dabaa": "الضبعة",
  "El Hamam": "الحمام",
  "El Negaila": "النجيلة",
  "Sidi Barrani": "سيدي براني",
  "Sallum": "السلوم",
  
  // North Sinai Governorate
  "El Arish": "العريش",
  "Sheikh Zuweid": "الشيخ زويد",
  "Rafah": "رفح",
  "Bir El Abd": "بئر العبد",
  "El Hasana": "الحسنة",
  "Nakhl": "نخل",
  "Sheikh Zuweid": "الشيخ زويد",
  "Rafah": "رفح",
  "Bir El Abd": "بئر العبد",
  "El Hasana": "الحسنة",
  "Nakhl": "نخل",
  
  // South Sinai Governorate
  "El Tor": "الطور",
  "Saint Catherine": "سانت كاترين",
  "Dahab": "دهب",
  "Nuweiba": "نويبع",
  "Sharm El Sheikh": "شرم الشيخ",
  "Taba": "طابا",
  "Saint Catherine": "سانت كاترين",
  "Dahab": "دهب",
  "Nuweiba": "نويبع",
  "Sharm El Sheikh": "شرم الشيخ",
  "Taba": "طابا"
};

// Complete list of Egyptian cities in Arabic with English keys
export const egyptianCities = [
  { value: "Cairo", label: "القاهرة" },
  { value: "Giza", label: "الجيزة" },
  { value: "Alexandria", label: "الإسكندرية" },
  { value: "Port Said", label: "بورسعيد" },
  { value: "Suez", label: "السويس" },
  { value: "Ismailia", label: "الإسماعيلية" },
  { value: "Damietta", label: "دمياط" },
  { value: "Mansoura", label: "المنصورة" },
  { value: "Tanta", label: "طنطا" },
  { value: "Shibin El Kom", label: "شبين الكوم" },
  { value: "Banha", label: "بنها" },
  { value: "Zagazig", label: "الزقازيق" },
  { value: "Kafr El Sheikh", label: "كفر الشيخ" },
  { value: "Damanhour", label: "دمنهور" },
  { value: "Fayoum", label: "الفيوم" },
  { value: "Beni Suef", label: "بني سويف" },
  { value: "Minya", label: "المنيا" },
  { value: "Assiut", label: "أسيوط" },
  { value: "Sohag", label: "سوهاج" },
  { value: "Qena", label: "قنا" },
  { value: "Luxor", label: "الأقصر" },
  { value: "Aswan", label: "أسوان" },
  { value: "Hurghada", label: "الغردقة" },
  { value: "El Kharga", label: "الخارجة" },
  { value: "Marsa Matrouh", label: "مرسى مطروح" },
  { value: "El Arish", label: "العريش" },
  { value: "El Tor", label: "الطور" },
  { value: "Helwan", label: "حلوان" },
  { value: "6th of October", label: "السادس من أكتوبر" },
  { value: "Sheikh Zayed", label: "الشيخ زايد" },
  { value: "New Cairo", label: "القاهرة الجديدة" },
  { value: "Shoubra", label: "شبرا" },
  { value: "Maadi", label: "المعادي" },
  { value: "Zamalek", label: "الزمالك" },
  { value: "Nasr City", label: "مدينة نصر" },
  { value: "Heliopolis", label: "مصر الجديدة" },
  { value: "Ain Shams", label: "عين شمس" },
  { value: "El Mokattam", label: "المقطم" },
  { value: "El Basatin", label: "البساتين" },
  { value: "El Sayeda Zeinab", label: "السيدة زينب" },
  { value: "El Darb El Ahmar", label: "الدرب الأحمر" },
  { value: "El Gamaleya", label: "الجمالية" },
  { value: "El Khalifa", label: "الخليفة" },
  { value: "El Mounira", label: "المنيرة" },
  { value: "El Sakakini", label: "السكاكيني" },
  { value: "El Shorouk", label: "الشروق" },
  { value: "El Tagamoa El Khames", label: "التجمع الخامس" },
  { value: "El Rehab", label: "الرحاب" },
  { value: "El Obour", label: "العبور" },
  { value: "El Badrasheen", label: "البدرشين" },
  { value: "El Haram", label: "الهرم" },
  { value: "El Hawamdeya", label: "الحوامدية" },
  { value: "El Saff", label: "الصف" },
  { value: "El Ayyat", label: "العياط" },
  { value: "El Kattameya", label: "القطامية" },
  { value: "Dokki", label: "الدقي" },
  { value: "Mohandessin", label: "المهندسين" },
  { value: "Agouza", label: "العجوزة" },
  { value: "Faisal", label: "فيصل" },
  { value: "Omraneya", label: "العمرانية" },
  { value: "Boulaq El Dakrour", label: "بولاق الدكرور" },
  { value: "Borg El Arab", label: "برج العرب" },
  { value: "Borg El Arab Industrial", label: "برج العرب الصناعية" },
  { value: "El Amreya", label: "العامرية" },
  { value: "El Agami", label: "العجمي" },
  { value: "El Dekheila", label: "الدخيلة" },
  { value: "El Montazah", label: "المنتزه" },
  { value: "El Raml", label: "الرمل" },
  { value: "El Gomrok", label: "الجمهور" },
  { value: "El Labban", label: "اللبان" },
  { value: "El Mansheya", label: "المنشية" },
  { value: "El Moharam Bek", label: "المحرم بك" },
  { value: "El Saba Pasha", label: "سابا باشا" },
  { value: "El Shatby", label: "الشاطبي" },
  { value: "El Wardian", label: "الورديان" },
  { value: "Karmouz", label: "كرموز" },
  { value: "Miami", label: "ميامي" },
  { value: "Sidi Gaber", label: "سيدي جابر" },
  { value: "Smouha", label: "سموحة" },
  { value: "Stanley", label: "ستانلي" },
  { value: "Victoria", label: "فيكتوريا" },
  { value: "Port Fouad", label: "بورفؤاد" },
  { value: "El Arab", label: "العرب" },
  { value: "El Sharq", label: "الشرق" },
  { value: "El Manakh", label: "المناخ" },
  { value: "El Zohour", label: "الزهور" },
  { value: "El Dawahy", label: "الضواحي" },
  { value: "El Salam", label: "السلام" },
  { value: "El Shohada", label: "الشهداء" },
  { value: "El Arbaeen", label: "الأربعين" },
  { value: "Attaka", label: "عتاقة" },
  { value: "El Ganayen", label: "الجنائن" },
  { value: "El Qantara", label: "القطارة" },
  { value: "El Qantara Sharq", label: "القطارة شرق" },
  { value: "Fayed", label: "فايد" },
  { value: "El Tal El Kebir", label: "التل الكبير" },
  { value: "Abu Suweir", label: "أبو صوير" },
  { value: "Kassaseen", label: "القصاصين" },
  { value: "Ras El Bar", label: "رأس البر" },
  { value: "El Zarqa", label: "الزرقا" },
  { value: "Kafr Saad", label: "كفر سعد" },
  { value: "Kafr El Battikh", label: "كفر البطيخ" },
  { value: "El Senga", label: "السناجا" },
  { value: "Miet Abou Ghalib", label: "ميت أبو غالب" },
  { value: "El Nour", label: "النور" },
  { value: "El Qod", label: "القد" },
  { value: "Talkha", label: "طلخا" },
  { value: "Mit Ghamr", label: "ميت غمر" },
  { value: "Dekernes", label: "دكرنس" },
  { value: "Aga", label: "أجا" },
  { value: "Minyet El Nasr", label: "منية النصر" },
  { value: "Sinbillawin", label: "سنبلاوين" },
  { value: "El Kurdi", label: "الكردي" },
  { value: "Bani Ebeid", label: "بني عبيد" },
  { value: "El Matareya", label: "المطرية" },
  { value: "Belqas", label: "بلقاس" },
  { value: "Sherbin", label: "شربين" },
  { value: "El Senbellawein", label: "السنبلاوين" },
  { value: "El Gamaliya", label: "الجمالية" },
  { value: "El Manzala", label: "المنزلة" },
  { value: "Temay El Amdid", label: "تمي الأمديد" },
  { value: "El Zarka", label: "الزرقا" },
  { value: "Shirbin", label: "شربين" },
  { value: "Mit El Kholy", label: "ميت الخولي" },
  { value: "El Mahalla El Kubra", label: "المحلة الكبرى" },
  { value: "Kafr El Zayat", label: "كفر الزيات" },
  { value: "Zefta", label: "زفتى" },
  { value: "El Santa", label: "السنطة" },
  { value: "Qutur", label: "قطور" },
  { value: "Basyoun", label: "بسيون" },
  { value: "Samanoud", label: "سمنود" },
  { value: "El Hamool", label: "الحامول" },
  { value: "Kotour", label: "قطور" },
  { value: "El Bagour", label: "الباجور" },
  { value: "Quesna", label: "قويسنا" },
  { value: "El Shohada", label: "الشهداء" },
  { value: "Tala", label: "تلا" },
  { value: "Berket El Sabaa", label: "بركة السبع" },
  { value: "El Sadat", label: "السادات" },
  { value: "Menouf", label: "منوف" },
  { value: "Ashmoun", label: "أشمون" },
  { value: "El Qanatir El Khairiya", label: "القناطر الخيرية" },
  { value: "Tukh", label: "طوخ" },
  { value: "Qalyub", label: "قليوب" },
  { value: "El Khanka", label: "الخانكة" },
  { value: "Kafr Shukr", label: "كفر شكر" },
  { value: "Shubra El Kheima", label: "شبرا الخيمة" },
  { value: "El Husseiniya", label: "الحسينية" },
  { value: "Abu Hammad", label: "أبو حماد" },
  { value: "El Qurein", label: "القرين" },
  { value: "Abu Kebir", label: "أبو كبير" },
  { value: "Faqous", label: "فاقوس" },
  { value: "El Ibrahimiya", label: "الإبراهيمية" },
  { value: "Hihya", label: "ههيا" },
  { value: "Awlad Saqr", label: "أولاد صقر" },
  { value: "El Salhiya", label: "الصالحية" },
  { value: "Minshat El Qanater", label: "منشأة القناطر" },
  { value: "Mashtoul El Souq", label: "مشتول السوق" },
  { value: "Qenaiat", label: "قنايات" },
  { value: "El Qanayat", label: "القنايات" },
  { value: "Desouk", label: "دسوق" },
  { value: "Fuwa", label: "فوة" },
  { value: "Metoubes", label: "مطوبس" },
  { value: "Baltim", label: "بلطيم" },
  { value: "Sidi Salem", label: "سيدي سالم" },
  { value: "Qallin", label: "قلين" },
  { value: "Sidi Ghazi", label: "سيدي غازي" },
  { value: "Biyala", label: "بيالة" },
  { value: "El Reyad", label: "الرياض" },
  { value: "El Borollos", label: "البرلس" },
  { value: "Rashid", label: "رشيد" },
  { value: "Kafr El Dawwar", label: "كفر الدوار" },
  { value: "Abu El Matamir", label: "أبو المطامير" },
  { value: "Abu Hummus", label: "أبو حمص" },
  { value: "El Delengat", label: "الدلنجات" },
  { value: "El Mahmoudiya", label: "المحمودية" },
  { value: "El Rahmaniya", label: "الرحمانية" },
  { value: "Edko", label: "إدكو" },
  { value: "Kom Hamada", label: "كوم حمادة" },
  { value: "El Nubaria", label: "النوبارية" },
  { value: "Wadi El Natrun", label: "وادي النطرون" },
  { value: "Fayoum El Gedida", label: "الفيوم الجديدة" },
  { value: "Tamiya", label: "طامية" },
  { value: "Sinnuris", label: "سنورس" },
  { value: "Etsa", label: "إطسا" },
  { value: "El Atsa", label: "العاطس" },
  { value: "Yousef El Seddik", label: "يوسف الصديق" },
  { value: "El Fashn", label: "الفحص" },
  { value: "Biyaso", label: "بياضو" },
  { value: "El Wasta", label: "الوسطى" },
  { value: "Nasser", label: "ناصر" },
  { value: "El Minya", label: "المنيا" },
  { value: "Maghagha", label: "مغاغة" },
  { value: "Beni Mazar", label: "بني مزار" },
  { value: "Matai", label: "مطاي" },
  { value: "Samalut", label: "سمالوط" },
  { value: "El Idwa", label: "العدوة" },
  { value: "Mallawi", label: "ملوي" },
  { value: "Deir Mawas", label: "دير مواس" },
  { value: "Abu Qurqas", label: "أبو قرقاص" },
  { value: "El Fath", label: "الفتح" },
  { value: "Abu Tig", label: "أبو تيج" },
  { value: "El Ghanayem", label: "الغنايم" },
  { value: "Sahel Selim", label: "ساحل سليم" },
  { value: "El Badari", label: "البداري" },
  { value: "Sidfa", label: "صدفا" },
  { value: "El Qusiya", label: "القسية" },
  { value: "Manfalut", label: "منفلوط" },
  { value: "Akhmim", label: "أخميم" },
  { value: "El Balyana", label: "البلينا" },
  { value: "El Maragha", label: "المراغة" },
  { value: "El Monshah", label: "المنشأة" },
  { value: "Dar El Salam", label: "دار السلام" },
  { value: "Girga", label: "جرجا" },
  { value: "Tahta", label: "طهطا" },
  { value: "El Waqf", label: "الوقف" },
  { value: "Qus", label: "قوص" },
  { value: "Naqada", label: "نقادة" },
  { value: "Farshout", label: "فرشوط" },
  { value: "Abu Tesht", label: "أبو تشت" },
  { value: "El Karnak", label: "الكرنك" },
  { value: "El Armant", label: "الأرمنت" },
  { value: "Esna", label: "إسنا" },
  { value: "El Tod", label: "الطود" },
  { value: "El Bayadiya", label: "البياضية" },
  { value: "El Qarna", label: "القرنة" },
  { value: "Abu Simbel", label: "أبو سمبل" },
  { value: "Kalabsha", label: "كلابشة" },
  { value: "Edfu", label: "إدفو" },
  { value: "Kom Ombo", label: "كوم أمبو" },
  { value: "Daraw", label: "دراو" },
  { value: "El Gouna", label: "الجونة" },
  { value: "Safaga", label: "سفاجا" },
  { value: "El Quseir", label: "القصير" },
  { value: "Marsa Alam", label: "مرسى علم" },
  { value: "Shalateen", label: "شلاتين" },
  { value: "Halayeb", label: "حلايب" },
  { value: "El Dakhla", label: "الداخلة" },
  { value: "El Farafra", label: "الفرافرة" },
  { value: "El Bahariya", label: "البحرية" },
  { value: "El Alamein", label: "العلمين" },
  { value: "El Dabaa", label: "الضبعة" },
  { value: "El Hamam", label: "الحمام" },
  { value: "El Negaila", label: "النجيلة" },
  { value: "Sidi Barrani", label: "سيدي براني" },
  { value: "Sallum", label: "السلوم" },
  { value: "Sheikh Zuweid", label: "الشيخ زويد" },
  { value: "Rafah", label: "رفح" },
  { value: "Bir El Abd", label: "بئر العبد" },
  { value: "El Hasana", label: "الحسنة" },
  { value: "Nakhl", label: "نخل" },
  { value: "Saint Catherine", label: "سانت كاترين" },
  { value: "Dahab", label: "دهب" },
  { value: "Nuweiba", label: "نويبع" },
  { value: "Sharm El Sheikh", label: "شرم الشيخ" },
  { value: "Taba", label: "طابا" }
];

// Function to get Arabic name from English name
export const getArabicCity = (englishName) => {
  return cityMapping[englishName] || englishName;
};

// Function to get English name from Arabic name  
export const getEnglishCity = (arabicName) => {
  const entry = Object.entries(cityMapping).find(([eng, ar]) => ar === arabicName);
  return entry ? entry[0] : arabicName;
};
